name: Build and Test

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version check
      run: xcodebuild -version
    - name: Check version
      run: swift --version
    - name: Build
      run: xcodebuild -scheme SwiftWebServer -destination "platform=OS X"
    - name: Test
      run: xcodebuild -scheme SwiftWebServer -destination "platform=OS X" test
